builds:
  -
    ldflags: -s -w -X github.com/bpineau/cloud-floating-ip/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

release:
  # don't autopublish
  draft: true

archive:
  format: binary

